[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "surjectors"
description = "Surjection layers for density estimation with normalizing flows"
authors = [{name = "Simon Dirmeier", email = "sfyrbnd@pm.me"}]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/dirmeier/surjectors"
keywords = ["normalizing flows", "surjections", "density estimation"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.9"
dependencies = [
    "distrax>=0.1.4",
    "dm-haiku>=0.0.10",
    "jaxlib>=0.4.18",
    "jax>=0.4.18",
    "optax>=0.1.7"
]
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/dirmeier/surjectors"

[tool.hatch.version]
path = "surjectors/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
    "./gitignore",
    "/.pre-commit-config.yaml"
]

[tool.hatch.envs.examples]
dependencies = [
    "matplotlib>=3.6.1"
]

[tool.hatch.envs.test]
dependencies = [
    "ruff>=0.3.0",
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0"
]

[tool.hatch.envs.test.scripts]
lint = 'ruff check surjectors'
test = 'pytest -v --cov=./surjectors --cov-report=xml surjectors'

[tool.isort]
profile = "black"
line_length = 80
include_trailing_comma = true

[tool.pylint.messages_control]
disable = """
invalid-name,missing-module-docstring,R0801
"""

[tool.bandit]
skips = ["B101"]

[tool.ruff]
line-length = 80
exclude = ["*_test.py", "docs/**", "examples/**"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = [
  "UP", "D", "I", "PL", "S"
]

[tool.ruff.lint.pydocstyle]
convention= 'google'
