[tool.poetry]
name = "surjectors"
version = "0.0.1"
description = "Inference surjection layers"
authors = ["Simon Dirmeier <sfyrbnd @ pm me>"]
readme = "README.md"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.dependencies]
python = "^3.9,<3.10"
jaxlib = "^0.3.22"
jax = "^0.3.23"
distrax = "^0.1.2"
dm-haiku = "^0.0.8"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = "^22.8.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "^0.971"
bandit = "^1.7.4"


[tool.black]
line-length = 80
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.isort]
profile = "black"
line_length = 80
include_trailing_comma = true
