[tool.poetry]
name = "surjectors"
version = "0.0.1"
description = "Inference surjection layers"
authors = ["Simon Dirmeier <sfyrbnd@pm.me>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/dirmeier/surjectors"
keywords = ["normalizing flows", "surjections", "density estimation"]
classifiers=[
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.dependencies]
python = "^3.9,<3.10"
distrax = "^0.1.2"
dm-haiku = "^0.0.9"
optax = "^0.1.3"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = "^22.8.0"
flake8 = "^5.0.4"
flake8-pyproject = "^1.1.0.post0"
isort = "^5.10.1"
mypy = "^0.971"
bandit = "^1.7.4"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"


[tool.black]
line-length = 80
extend-ignore = "E203"
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.isort]
profile = "black"
line_length = 80
include_trailing_comma = true

[tool.flake8]
max-line-length = 80
extend-ignore = ["E203", "W503"]
